# Generated by Django 3.1.5 on 2021-01-31 07:11

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('organisation', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('Investors', models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('Queries', models.TextField(max_length=10000)),
                ('upload_file', models.FileField(upload_to='contact/')),
            ],
        ),
    ]
