# Generated by Django 3.1.5 on 2021-02-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Investors',
            field=models.CharField(choices=[('Customer (potential/existing)', (('request', 'Request for Services'),)), ('Other Queries', (('analyst', 'Analysts (Industry and Financial)'), ('investor', 'Investors'), ('media', 'Media and Journalists'), ('global', 'Global Procurement Services'), ('security', 'Report a Security Incident')))], max_length=50),
        ),
    ]
