# Generated by Django 3.1.5 on 2021-02-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_model',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='blog_model',
            name='blog_status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'UnPublished'), (2, 'Published')], default=0),
        ),
    ]
